// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Bias Story",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Bias Story",
            targets: ["AppModule"],
            bundleIdentifier: "eduardo.Bias-Story",
            teamIdentifier: "JV6QJM67FK",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .twoPeople),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)